{
  self,
  pkgs,
  ...
}:
let
  userName = "nick";
in
{
  imports = [
    # Hardware-specific configuration (auto-generated)
    # Generated by `nixos-generate-config --no-filesystems`
    ./hardware-configuration.nix

    # Disk partitioning and filesystem configuration
    # Managed by the `disko` utility for declarative disk management
    ./disko-config.nix

    # Shared Nix settings
    self.nixosModules.nix-config

    # Core system configuration and essential utilities
    self.nixosModules.core
  ];

  # Boot manager
  boot.loader.systemd-boot.enable = true;

  # System Hostname
  networking.hostName = "atlas";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/Bucharest";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  # User
  users.mutableUsers = true;
  users.enforceIdUniqueness = true; # Require unique UIDs/GIDs
  users.users."${userName}" = {
    name = userName;
    isNormalUser = true;

    home = "/home/${userName}";
    createHome = true;

    useDefaultShell = false;
    shell = pkgs.bashInteractive;

    group = userName; # UPG
    extraGroups = [
      "wheel" # Grants sudo privileges
      "networkmanager"
    ];

    # The initial password is meant to be changed right away. It's purpose is to
    # enable installing without a root password.
    initialPassword = userName;
  };
  # UPG
  users.groups."${userName}" = {
    name = userName;
    members = [ userName ];
  };

  # Automatic Nix garbage collection config
  nix.gc.automatic = false;

  # SSH
  services.openssh = {
    enable = true;
    ports = [ 22 ];
    settings = {
      PasswordAuthentication = false;
      AllowUsers = [ "nick" ];
      UseDns = true;
      PermitRootLogin = "no";
    };
    authorizedKeysInHomedir = true;
  };

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "24.11";
}
